# -*- coding: utf-8 -*-
"""ML_project_DEPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZL5KZZ6Qksr4r0KMVrDyiHqjjlnCRMX2
"""

# ==== Cell 0 (NEW) – Pin scikit-learn to match the Streamlit Cloud deployment ====
# This must run BEFORE any sklearn import, and BEFORE training, so every model
# in this notebook is trained/pickled with the exact same sklearn version that
# will later unpickle it in the deployed app. Mismatched versions are what caused
# the ModuleNotFoundError / AttributeError when loading the .pkl files in Streamlit.
#
# IMPORTANT (Colab): after this cell finishes, if it PRINTS an OLD version below
# instead of 1.9.0, go to Runtime > Restart runtime, then re-run this cell first,
# BEFORE running any other cell in the notebook (Colab caches already-imported
# packages in memory, so a plain pip install isn't always enough).
!pip install -q ydata-profiling
!pip install -q scikit-learn==1.9.0

import sklearn
print("scikit-learn version:", sklearn.__version__)
assert sklearn.__version__ == "1.9.0", (
    "sklearn version mismatch — restart the runtime and re-run this cell FIRST, "
    "before any other cell."
)

# ========== basics ==========
import re
import json
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport
warnings.filterwarnings("ignore")

# ==========   saving ==========
import joblib
import pickle
from datasets import load_dataset
import ast

# ========== Scikit-learn:   ==========
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV, cross_val_score, KFold
from sklearn.metrics import (
    accuracy_score, confusion_matrix, classification_report,
    mean_squared_error, r2_score, roc_curve, auc, ConfusionMatrixDisplay
)

# ========== Scikit-learn:   ==========
from sklearn.preprocessing import (
    LabelEncoder, OneHotEncoder, StandardScaler, MinMaxScaler, PolynomialFeatures
)
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin

# ========== Scikit-learn:   ==========
from sklearn.linear_model import (
    LinearRegression, Lasso, Ridge, ElasticNet, LassoCV, HuberRegressor, LogisticRegression
)
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, plot_tree
from sklearn.ensemble import (
    RandomForestClassifier, RandomForestRegressor, GradientBoostingClassifier
)
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.svm import SVC, LinearSVC, SVR
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB, ComplementNB
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor, NearestNeighbors

# ========== Scikit-learn: ==========
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity, linear_kernel
from xgboost import XGBClassifier
from sklearn.feature_selection import chi2

from google.colab import drive               # the library that connects notebook with the drive to read the dataset
drive.mount('/content/drive')                # connection with my drive
file_path = '/content/drive/My Drive/datasets/dataset.csv' # dataset path
df = pd.read_csv(file_path)   # read the dataset and convert it from CSV to dataframe
pd.set_option('display.max_columns',len(df.columns)) # adjusting style
df.rename(columns=lambda x: x.strip().lower().replace(' ', '_'), inplace=True)
df

df.info() # get the schema, data type and memory usage

df.describe(include="all") # analyze the data

df.isna().sum().to_frame() # compute the Null value

df.drop(['complectation'], axis=1, inplace=True) # drop the unuseful columns

df.drop(['super_gen_name'], axis=1, inplace=True) # drop the unuseful columns

df.dropna(inplace=True)

print(df.duplicated().sum()) # compute the duplicated value

df.drop_duplicates(inplace=True) # drop the duplicated value

df.head(5) # show the first 5 rows

columns = df.columns
columns

continuous_col = df.select_dtypes(include=['float64', 'int64']).columns
continuous_col = [col for col in continuous_col if col != 'price']
categorical_col = df.select_dtypes(include=['object', 'category']).columns  #classifiy the categorical columns

print(categorical_col)
print(continuous_col)

for i in categorical_col:
    print(df.value_counts(i))

dist = df[continuous_col] #represent the numerical data distrubutions
dist.hist(figsize=(15, 10), bins=20) #visualize histogram using matplotlib
plt.show()

fig, axes = plt.subplots(len(categorical_col), 1, figsize=(10, 4 * len(categorical_col)))
for i, col in enumerate(categorical_col):
    ax = axes[i]
    sns.countplot(data=df, x=col, order=df[col].value_counts().index[:10], ax=ax)
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45)
    ax.set_title(f'Distribution of {col}')
    ax.set_xlabel(col)
    ax.set_ylabel('Count')

plt.tight_layout()
plt.show()

corr_matrix = df[continuous_col].corr()
plt.figure(figsize=(20, 10))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

df[continuous_col].skew()

def detect_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return data[(data[column] < lower_bound) | (data[column] > upper_bound)]

for col in continuous_col:
    outliers = detect_outliers_iqr(df, col)
    print(f"Number of outliers in {col}: {len(outliers)}")

from scipy.stats.mstats import winsorize
import pandas as pd

def detect_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)]
    return outliers, lower_bound, upper_bound

def apply_winsorization(data, continuous_cols, lower_pct=0.01, upper_pct=0.01, apply=True):
    df_copy = data.copy()
    summary = {}

    for col in continuous_cols:
        outliers, low, high = detect_outliers_iqr(df_copy, col)
        n_out_before = len(outliers)

        if not apply:
            summary[col] = {
                "outliers_before": n_out_before,
                "outliers_after": n_out_before,
                "winsorized": False
            }
            continue

        df_copy[col] = winsorize(df_copy[col], limits=[lower_pct, upper_pct])
        outliers_after, _, _ = detect_outliers_iqr(df_copy, col)
        n_out_after = len(outliers_after)

        summary[col] = {
            "outliers_before": n_out_before,
            "outliers_after": n_out_after,
            "winsorized": True
        }

    return df_copy, summary

clean_df, outlier_report = apply_winsorization(
    df,
    continuous_col,
    lower_pct=0.01,
    upper_pct=0.01,
    apply=True
)

print("\nOutlier Report (Before vs After Winsorization):\n")
for col, stats in outlier_report.items():
    print(f"{col:25} | before={stats['outliers_before']:5} | after={stats['outliers_after']:5} | winsorized={stats['winsorized']}")

for col in continuous_col:
    plt.figure(figsize=(12, 5))
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot of {col}")
    plt.show()

def remove_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return data[(data[column] >= lower_bound) & (data[column] <= upper_bound)]

for col in continuous_col:
    df = remove_outliers_iqr(df, col)

print(f"Dataset shape after removing outliers: {df.shape}")

from scipy.stats.mstats import winsorize
import pandas as pd

def detect_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)]
    return outliers, lower_bound, upper_bound

def apply_winsorization(data, continuous_cols, lower_pct=0.01, upper_pct=0.01, apply=True):
    df_copy = data.copy()
    summary = {}

    for col in continuous_cols:
        outliers, low, high = detect_outliers_iqr(df_copy, col)
        n_out_before = len(outliers)

        if not apply:
            summary[col] = {
                "outliers_before": n_out_before,
                "outliers_after": n_out_before,
                "winsorized": False
            }
            continue

        df_copy[col] = winsorize(df_copy[col], limits=[lower_pct, upper_pct])
        outliers_after, _, _ = detect_outliers_iqr(df_copy, col)
        n_out_after = len(outliers_after)

        summary[col] = {
            "outliers_before": n_out_before,
            "outliers_after": n_out_after,
            "winsorized": True
        }

    return df_copy, summary

clean_df, outlier_report = apply_winsorization(
    df,
    continuous_col,
    lower_pct=0.01,
    upper_pct=0.01,
    apply=True
)

print("\nOutlier Report (Before vs After Winsorization):\n")
for col, stats in outlier_report.items():
    print(f"{col:25} | before={stats['outliers_before']:5} | after={stats['outliers_after']:5} | winsorized={stats['winsorized']}")

df_copy = df.copy()
categorical_col = df_copy.select_dtypes(include=['object', 'category']).columns

df_copy['price_bin'] = pd.qcut(df_copy['price'], q=5, labels=False)
target = 'price_bin'

chi2_results = {}
le = LabelEncoder()

for col in categorical_col:
    if col == target:
        continue
    feature_encoded = le.fit_transform(df_copy[col])
    target_encoded = le.fit_transform(df_copy[target])
    chi2_stat, p_val = chi2(feature_encoded.reshape(-1, 1), target_encoded)
    chi2_results[col] = p_val[0]

important_cols = [col for col, p in chi2_results.items() if p < 0.05]
print(important_cols)

import pandas as pd
from scipy.stats import f_oneway

anova_results = {}

for col in categorical_col:
    groups = [df['price'][df[col] == cat] for cat in df[col].dropna().unique()]
    if len(groups) > 1:
        f_stat, p_val = f_oneway(*groups)
        anova_results[col] = p_val

important_cols = [col for col, p in anova_results.items() if p < 0.05]
print("Columns significantly correlated with price:", important_cols)

df_encoded = df.copy()
categorical_col = df_encoded.select_dtypes(include=['object', 'category']).columns

le = LabelEncoder()
for col in categorical_col:
    df_encoded[col] = le.fit_transform(df_encoded[col].astype(str))

scaler = MinMaxScaler()
df_encoded[continuous_col] = scaler.fit_transform(df_encoded[continuous_col])

df_encoded

# ==== Cell 1 – Train/Test Split + Setup ====

from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# X = all features except price, y = target price
X = df_encoded.drop(columns=['price'])
y = df_encoded['price']

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Dictionary to store R2 scores of each model for comparison
model_results = {}

# ==== Cell 2 – Linear Regression ====

from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()

# Simple hyperparameter space for RandomizedSearchCV
lin_param_dist = {
    'fit_intercept': [True, False],
    'positive': [True, False]
}

lin_rand_search = RandomizedSearchCV(
    estimator=lin_reg,
    param_distributions=lin_param_dist,
    n_iter=10,
    scoring='r2',
    cv=3,
    n_jobs=-1,
    random_state=42,
    verbose=1
)

lin_rand_search.fit(X_train, y_train)

best_lin = lin_rand_search.best_estimator_
y_pred_lin = best_lin.predict(X_test)

rmse_lin = np.sqrt(mean_squared_error(y_test, y_pred_lin))
mae_lin = mean_absolute_error(y_test, y_pred_lin)
r2_lin = r2_score(y_test, y_pred_lin)

print("=== Linear Regression ===")
print("Best params:", lin_rand_search.best_params_)
print(f"RMSE: {rmse_lin:.4f}")
print(f"MAE : {mae_lin:.4f}")
print(f"R²  : {r2_lin:.4f}")

model_results['LinearRegression'] = r2_lin

# ==== Cell 3 – Ridge Regression ====

from sklearn.linear_model import Ridge

ridge = Ridge(random_state=42)

ridge_param_dist = {
    'alpha': np.logspace(-3, 3, 50)
}

ridge_rand_search = RandomizedSearchCV(
    estimator=ridge,
    param_distributions=ridge_param_dist,
    n_iter=20,
    scoring='r2',
    cv=3,
    n_jobs=-1,
    random_state=42,
    verbose=1
)

ridge_rand_search.fit(X_train, y_train)

best_ridge = ridge_rand_search.best_estimator_
y_pred_ridge = best_ridge.predict(X_test)

rmse_ridge = np.sqrt(mean_squared_error(y_test, y_pred_ridge))
mae_ridge = mean_absolute_error(y_test, y_pred_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

print("=== Ridge Regression ===")
print("Best params:", ridge_rand_search.best_params_)
print(f"RMSE: {rmse_ridge:.4f}")
print(f"MAE : {mae_ridge:.4f}")
print(f"R²  : {r2_ridge:.4f}")

model_results['Ridge'] = r2_ridge

# ==== Cell 4 – Lasso Regression ====

from sklearn.linear_model import Lasso

lasso = Lasso(random_state=42, max_iter=10000)

lasso_param_dist = {
    'alpha': np.logspace(-4, 1, 50)
}

lasso_rand_search = RandomizedSearchCV(
    estimator=lasso,
    param_distributions=lasso_param_dist,
    n_iter=20,
    scoring='r2',
    cv=3,
    n_jobs=-1,
    random_state=42,
    verbose=1
)

lasso_rand_search.fit(X_train, y_train)

best_lasso = lasso_rand_search.best_estimator_
y_pred_lasso = best_lasso.predict(X_test)

rmse_lasso = np.sqrt(mean_squared_error(y_test, y_pred_lasso))
mae_lasso = mean_absolute_error(y_test, y_pred_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)

print("=== Lasso Regression ===")
print("Best params:", lasso_rand_search.best_params_)
print(f"RMSE: {rmse_lasso:.4f}")
print(f"MAE : {mae_lasso:.4f}")
print(f"R²  : {r2_lasso:.4f}")

model_results['Lasso'] = r2_lasso

# ==== Cell 5 – Elastic Net Regression ====

from sklearn.linear_model import ElasticNet

elastic = ElasticNet(random_state=42, max_iter=10000)

elastic_param_dist = {
    'alpha': np.logspace(-4, 1, 50),
    'l1_ratio': np.linspace(0.1, 0.9, 9)
}

elastic_rand_search = RandomizedSearchCV(
    estimator=elastic,
    param_distributions=elastic_param_dist,
    n_iter=30,
    scoring='r2',
    cv=3,
    n_jobs=-1,
    random_state=42,
    verbose=1
)

elastic_rand_search.fit(X_train, y_train)

best_elastic = elastic_rand_search.best_estimator_
y_pred_elastic = best_elastic.predict(X_test)

rmse_elastic = np.sqrt(mean_squared_error(y_test, y_pred_elastic))
mae_elastic = mean_absolute_error(y_test, y_pred_elastic)
r2_elastic = r2_score(y_test, y_pred_elastic)

print("=== Elastic Net ===")
print("Best params:", elastic_rand_search.best_params_)
print(f"RMSE: {rmse_elastic:.4f}")
print(f"MAE : {mae_elastic:.4f}")
print(f"R²  : {r2_elastic:.4f}")

model_results['ElasticNet'] = r2_elastic

# ==== Cell 6 – Decision Tree Regressor ====

from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)

dt_param_dist = {
    'max_depth': [None] + list(range(3, 21)),
    'min_samples_split': [2, 5, 10, 15],
    'min_samples_leaf': [1, 2, 4, 8],
    'max_features': ['auto', 'sqrt', 'log2', None]
}

dt_rand_search = RandomizedSearchCV(
    estimator=dt,
    param_distributions=dt_param_dist,
    n_iter=40,
    scoring='r2',
    cv=3,
    n_jobs=-1,
    random_state=42,
    verbose=1
)

dt_rand_search.fit(X_train, y_train)

best_dt = dt_rand_search.best_estimator_
y_pred_dt = best_dt.predict(X_test)

rmse_dt = np.sqrt(mean_squared_error(y_test, y_pred_dt))
mae_dt = mean_absolute_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print("=== Decision Tree Regressor ===")
print("Best params:", dt_rand_search.best_params_)
print(f"RMSE: {rmse_dt:.4f}")
print(f"MAE : {mae_dt:.4f}")
print(f"R²  : {r2_dt:.4f}")

model_results['DecisionTree'] = r2_dt

# ==== Cell 8 – Simple Gradient Boosting Regressor ====

from sklearn.ensemble import GradientBoostingRegressor

# Simple, single configuration (no RandomizedSearch, no CV)
gbr = GradientBoostingRegressor(
    random_state=42,
    n_estimators=200,
    learning_rate=0.1,
    max_depth=3,
    subsample=0.8
)

gbr.fit(X_train, y_train)

y_pred_gbr = gbr.predict(X_test)

rmse_gbr = np.sqrt(mean_squared_error(y_test, y_pred_gbr))
mae_gbr = mean_absolute_error(y_test, y_pred_gbr)
r2_gbr = r2_score(y_test, y_pred_gbr)

print("=== Gradient Boosting Regressor (simple) ===")
print("Params used:")
print(gbr.get_params())
print(f"RMSE: {rmse_gbr:.4f}")
print(f"MAE : {mae_gbr:.4f}")
print(f"R²  : {r2_gbr:.4f}")

model_results['GradientBoosting'] = r2_gbr
best_gbr = gbr

# ==== Cell 12 – Plot Comparison of R² Scores ====

import matplotlib.pyplot as plt

# Sort models by R² descending
sorted_results = dict(sorted(model_results.items(), key=lambda x: x[1], reverse=True))

names = list(sorted_results.keys())
scores = list(sorted_results.values())

plt.figure(figsize=(10, 6))
plt.bar(range(len(names)), scores)
plt.xticks(range(len(names)), names, rotation=45, ha='right')
plt.ylabel('R² Score')
plt.title('Model Comparison on Test Set (R²)')
plt.ylim(0, 1)  # Adjust if needed depending on your results
plt.tight_layout()
plt.show()

print("R² scores by model:")
for name, score in sorted_results.items():
    print(f"{name:20s}: {score:.4f}")

# ==== Cell A – Save Encoders, Scaler, and Column Order ====

import joblib
from sklearn.preprocessing import LabelEncoder

# 1) Re-fit one LabelEncoder per categorical column on the ORIGINAL df
label_encoders = {}
categorical_cols = df.select_dtypes(include=["object", "category"]).columns

for col in categorical_cols:
    le = LabelEncoder()
    le.fit(df[col].astype(str))   # same mapping used when you encoded df_encoded
    label_encoders[col] = le

# Save all label encoders in one file
joblib.dump(label_encoders, "label_encoders.pkl")
print("Saved label_encoders.pkl")

# 2) Save the MinMaxScaler you already fitted on continuous_col
joblib.dump(scaler, "minmax_scaler.pkl")
print("Saved minmax_scaler.pkl")

# 3) Save the feature column order used for training (X columns)
joblib.dump(list(X.columns), "columns.pkl")
print("Saved columns.pkl")

# ==== Cell B – Save Trained Models and Best Model ====

import joblib

# Dictionary of all trained regression models
trained_models = {
    "LinearRegression": best_lin,
    "Ridge": best_ridge,
    "Lasso": best_lasso,
    "ElasticNet": best_elastic,
    "DecisionTree": best_dt,
    "GradientBoosting": best_gbr
}

# 1) Save each model separately
for name, model in trained_models.items():
    filename = f"{name}.pkl"
    joblib.dump(model, filename)
    print(f"Saved {filename}")

# 2) Also save the best model (based on R² in model_results)
best_model_name = max(model_results, key=model_results.get)
best_model = trained_models[best_model_name]

joblib.dump(best_model, "best_model.pkl")
print(f"Best model is: {best_model_name}")
print("Saved best_model.pkl")

# 3) Sanity check: confirm the sklearn version these were pickled with
import sklearn
print("Saved all artifacts using scikit-learn version:", sklearn.__version__)
print("Make sure Streamlit Cloud's requirements.txt pins the SAME version:")
print(f"scikit-learn=={sklearn.__version__}")

# ==== Cell C – Download Artifacts from Colab (Optional) ====

from google.colab import files

files.download("best_model.pkl")
files.download("label_encoders.pkl")
files.download("minmax_scaler.pkl")
files.download("columns.pkl")

# If you want specific models too:
# files.download("LinearRegression.pkl")
files.download("GradientBoosting.pkl")